=== Ahaochan/project/ahao-process-engine/ahao-process-engine-wrapper/src/main/resources/process-engine.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3school.com.cn"
           xmlns="http://www.w3school.com.cn"
           elementFormDefault="qualified">
    <!-- 定义<process-context>里的规则 -->
    <xs:element name="process-context">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <!-- 允许包含process标签 -->
                    <xs:element ref="process"/>
                    <xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- 定义<process>里的规则 -->
    <xs:element name="process">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <!-- 允许包含nodes和bizRelations标签 -->
                    <xs:element ref="nodes"/>
                    <xs:element ref="bizRelations"/>
                    <xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
                </xs:choice>
            </xs:sequence>
            <!-- <process>标签的name属性, 是必填的 -->
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="bizRelations">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="bizConfig"/>
                    <xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- 定义<nodes>里的规则 -->
    <xs:element name="nodes">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="node"/>
                    <xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- 定义<node>里的规则 -->
    <xs:element name="node">
        <xs:complexType>
            <!-- <node>标签的name属性, 是必填的 -->
            <xs:attribute name="name" type="xs:string" use="required"/>
            <!-- <node>标签的class属性, 是必填的 -->
            <xs:attribute name="class" type="xs:string" use="required"/>
            <!-- <node>标签的begin属性, 是可填的, 默认为false -->
            <xs:attribute name="begin" type="xs:boolean" use="optional" default="false"/>
            <!-- <node>标签的next属性, 是可填的, 默认为null -->
            <xs:attribute name="next" type="xs:string" use="optional"/>
            <!-- <node>标签的invoke-method属性, 是可填的, 默认为sync -->
            <xs:attribute name="invoke-method" type="xs:string" use="optional" default="sync"/>
        </xs:complexType>
    </xs:element>

    <!-- 定义<bizConfig>里的规则 -->
    <xs:element name="bizConfig">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="businessIdentifier" type="xs:integer" use="required"/>
            <xs:attribute name="orderType" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Ahaochan/project/ahao-process-engine/ahao-process-engine-wrapper/src/test/resources/process-no-begin.xml
<?xml version="1.0" encoding="UTF-8"?>
<process-context xmlns="http://www.w3school.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.w3school.com.cn process-engine.xsd">
    <process name="standard">
        <node name="A" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo" next="B" begin="true"/>
        <node name="B" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo" next="C"/>
        <node name="C" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo"/>
    </process>

    <process name="process-no-begin">
        <node name="A" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo" next="B"/>
        <node name="B" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo" next="C"/>
        <node name="C" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo"/>
    </process>
</process-context>

=== Ahaochan/project/ahao-process-engine/ahao-process-engine-wrapper/src/test/resources/process-demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<process-context xmlns="http://www.w3school.com.cn"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.w3school.com.cn process-engine.xsd">
    <process name="standard">
        <node name="A" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo" next="B" begin="true"/>
        <node name="B" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo" next="C"/>
        <node name="C" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo"/>
    </process>

    <process name="rollback">
        <node name="A" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo" next="B" begin="true"/>
        <node name="B" class="moe.ahao.process.engine.core.processor.RollbackOneProcessorDemo" next="C"/>
        <node name="C" class="moe.ahao.process.engine.core.processor.RollbackTwoProcessorDemo"/>
    </process>

    <process name="dynamic">
        <node name="A" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo" next="B" begin="true"/>
        <node name="B" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo" next="C"/>
        <node name="C" class="moe.ahao.process.engine.core.processor.DynamicProcessorDemo" next="D,E" />
        <node name="D" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo"/>
        <node name="E" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo"/>
    </process>

    <process name="process-async">
        <node name="node1" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo" next="node2"
              begin="true"/>
        <node name="node2" class="moe.ahao.process.engine.core.processor.RollbackOneProcessorDemo" next="node3"/>
        <node name="node3" class="moe.ahao.process.engine.core.processor.DynamicProcessorDemo" next="node4,node5"
              invoke-method="async"/>
        <node name="node4" class="moe.ahao.process.engine.core.processor.RollbackTwoProcessorDemo"/>
        <node name="node5" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo"/>
    </process>

    <process name="process2">
        <node name="node1" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo" next="node2"
              begin="true"/>
        <node name="node2" class="moe.ahao.process.engine.core.processor.RollbackOneProcessorDemo" next="node3"/>
        <node name="node3" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo" next="node4"/>
        <node name="node4" class="moe.ahao.process.engine.core.processor.RollbackTwoProcessorDemo" next="node5"/>
        <node name="node5" class="moe.ahao.process.engine.core.processor.StandardProcessorDemo"/>
    </process>
</process-context>

=== Ahaochan/project/ahao-process-engine/ahao-process-engine-demo/ahao-process-engine-demo-xml/src/main/resources/process-demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<process-context xmlns="http://www.w3school.com.cn"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.w3school.com.cn process-engine.xsd">
    <process name="process1">
        <node name="node1" class="com.ruyuan.process.engine.demo.StandardProcessorDemo" next="node2" begin="true"/>
        <node name="node2" class="com.ruyuan.process.engine.demo.RollBackProcessorDemo" next="node3"/>
        <node name="node3" class="com.ruyuan.process.engine.demo.DynamicProcessorDemo" next="node4,node5"/>
        <node name="node4" class="com.ruyuan.process.engine.demo.RollbackProcessorThrowExceptionDemo"/>
        <node name="node5" class="com.ruyuan.process.engine.demo.StandardProcessorDemo"/>
    </process>

    <process name="process-async">
        <node name="node1" class="com.ruyuan.process.engine.demo.StandardProcessorDemo" next="node2" begin="true"/>
        <node name="node2" class="com.ruyuan.process.engine.demo.RollBackProcessorDemo" next="node3"/>
        <node name="node3" class="com.ruyuan.process.engine.demo.DynamicProcessorDemo" next="node4,node5"
              invoke-method="async"/>
        <node name="node4" class="com.ruyuan.process.engine.demo.RollbackProcessorThrowExceptionDemo"/>
        <node name="node5" class="com.ruyuan.process.engine.demo.StandardProcessorDemo"/>
    </process>

    <process name="process2">
        <node name="node1" class="com.ruyuan.process.engine.demo.StandardProcessorDemo" next="node2" begin="true"/>
        <node name="node2" class="com.ruyuan.process.engine.demo.RollBackProcessorDemo" next="node3"/>
        <node name="node3" class="com.ruyuan.process.engine.demo.StandardProcessorDemo" next="node4"/>
        <node name="node4" class="com.ruyuan.process.engine.demo.RollbackProcessorThrowExceptionDemo" next="node5"/>
        <node name="node5" class="com.ruyuan.process.engine.demo.StandardProcessorDemo"/>
    </process>
</process-context>
